name: Lint code

on:
  push:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]
  pull_request:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies and ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run ruff linter
        run: |
          ruff check --ignore E501 --no-cache .
