name: Test pipeline

on:
  push:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]
  pull_request:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t urfu_sber:latest .

      - name: Run tests in Docker container
        run: |
          docker run --rm urfu_sber:latest pytest tests/
