name: Test pipeline

on:
  push:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]
  pull_request:
    branches: [ "develop", "main" ]
    paths: [ "docker-compose.yaml", "Dockerfile", "src/**", "tests/**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest tests/test_load_dataset.py
          pytest tests/test_model.py
          pytest tests/test_save_model.py
          pytest tests/test_spaces_in_dataset.py
